version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pictyschool
      PGUSER: docker
      PGPASSWORD: docker
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:16
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './api:/var/www:cached'
    command: npm run start:dev

  kit:
    image: node:16
    working_dir: '/var/www'
    depends_on:
      - api
    ports:
      - 24678:24678
    volumes:
      - './kit:/var/www:cached'
    command: npm run dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - 'kit'
      - 'api'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
